/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SonRouteImport } from './routes/son'
import { Route as ScoringRouteImport } from './routes/scoring'
import { Route as ScoreboardRouteImport } from './routes/scoreboard'
import { Route as ResolutionsRouteImport } from './routes/resolutions'
import { Route as ReseauRouteImport } from './routes/reseau'
import { Route as ProgressionRouteImport } from './routes/progression'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as LumieresRouteImport } from './routes/lumieres'
import { Route as DerouleRouteImport } from './routes/deroule'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustoRouteImport } from './routes/custo'
import { Route as ChronoRouteImport } from './routes/chrono'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as CamerasRouteImport } from './routes/cameras'
import { Route as AccueilRouteImport } from './routes/accueil'
import { Route as AccesRouteImport } from './routes/acces'
import { Route as IndexRouteImport } from './routes/index'

const SonRoute = SonRouteImport.update({
  id: '/son',
  path: '/son',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoringRoute = ScoringRouteImport.update({
  id: '/scoring',
  path: '/scoring',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreboardRoute = ScoreboardRouteImport.update({
  id: '/scoreboard',
  path: '/scoreboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ResolutionsRoute = ResolutionsRouteImport.update({
  id: '/resolutions',
  path: '/resolutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReseauRoute = ReseauRouteImport.update({
  id: '/reseau',
  path: '/reseau',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressionRoute = ProgressionRouteImport.update({
  id: '/progression',
  path: '/progression',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const LumieresRoute = LumieresRouteImport.update({
  id: '/lumieres',
  path: '/lumieres',
  getParentRoute: () => rootRouteImport,
} as any)
const DerouleRoute = DerouleRouteImport.update({
  id: '/deroule',
  path: '/deroule',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustoRoute = CustoRouteImport.update({
  id: '/custo',
  path: '/custo',
  getParentRoute: () => rootRouteImport,
} as any)
const ChronoRoute = ChronoRouteImport.update({
  id: '/chrono',
  path: '/chrono',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const CamerasRoute = CamerasRouteImport.update({
  id: '/cameras',
  path: '/cameras',
  getParentRoute: () => rootRouteImport,
} as any)
const AccueilRoute = AccueilRouteImport.update({
  id: '/accueil',
  path: '/accueil',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesRoute = AccesRouteImport.update({
  id: '/acces',
  path: '/acces',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acces': typeof AccesRoute
  '/accueil': typeof AccueilRoute
  '/cameras': typeof CamerasRoute
  '/challenges': typeof ChallengesRoute
  '/chrono': typeof ChronoRoute
  '/custo': typeof CustoRoute
  '/dashboard': typeof DashboardRoute
  '/deroule': typeof DerouleRoute
  '/lumieres': typeof LumieresRoute
  '/monitoring': typeof MonitoringRoute
  '/progression': typeof ProgressionRoute
  '/reseau': typeof ReseauRoute
  '/resolutions': typeof ResolutionsRoute
  '/scoreboard': typeof ScoreboardRoute
  '/scoring': typeof ScoringRoute
  '/son': typeof SonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acces': typeof AccesRoute
  '/accueil': typeof AccueilRoute
  '/cameras': typeof CamerasRoute
  '/challenges': typeof ChallengesRoute
  '/chrono': typeof ChronoRoute
  '/custo': typeof CustoRoute
  '/dashboard': typeof DashboardRoute
  '/deroule': typeof DerouleRoute
  '/lumieres': typeof LumieresRoute
  '/monitoring': typeof MonitoringRoute
  '/progression': typeof ProgressionRoute
  '/reseau': typeof ReseauRoute
  '/resolutions': typeof ResolutionsRoute
  '/scoreboard': typeof ScoreboardRoute
  '/scoring': typeof ScoringRoute
  '/son': typeof SonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acces': typeof AccesRoute
  '/accueil': typeof AccueilRoute
  '/cameras': typeof CamerasRoute
  '/challenges': typeof ChallengesRoute
  '/chrono': typeof ChronoRoute
  '/custo': typeof CustoRoute
  '/dashboard': typeof DashboardRoute
  '/deroule': typeof DerouleRoute
  '/lumieres': typeof LumieresRoute
  '/monitoring': typeof MonitoringRoute
  '/progression': typeof ProgressionRoute
  '/reseau': typeof ReseauRoute
  '/resolutions': typeof ResolutionsRoute
  '/scoreboard': typeof ScoreboardRoute
  '/scoring': typeof ScoringRoute
  '/son': typeof SonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acces'
    | '/accueil'
    | '/cameras'
    | '/challenges'
    | '/chrono'
    | '/custo'
    | '/dashboard'
    | '/deroule'
    | '/lumieres'
    | '/monitoring'
    | '/progression'
    | '/reseau'
    | '/resolutions'
    | '/scoreboard'
    | '/scoring'
    | '/son'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acces'
    | '/accueil'
    | '/cameras'
    | '/challenges'
    | '/chrono'
    | '/custo'
    | '/dashboard'
    | '/deroule'
    | '/lumieres'
    | '/monitoring'
    | '/progression'
    | '/reseau'
    | '/resolutions'
    | '/scoreboard'
    | '/scoring'
    | '/son'
  id:
    | '__root__'
    | '/'
    | '/acces'
    | '/accueil'
    | '/cameras'
    | '/challenges'
    | '/chrono'
    | '/custo'
    | '/dashboard'
    | '/deroule'
    | '/lumieres'
    | '/monitoring'
    | '/progression'
    | '/reseau'
    | '/resolutions'
    | '/scoreboard'
    | '/scoring'
    | '/son'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccesRoute: typeof AccesRoute
  AccueilRoute: typeof AccueilRoute
  CamerasRoute: typeof CamerasRoute
  ChallengesRoute: typeof ChallengesRoute
  ChronoRoute: typeof ChronoRoute
  CustoRoute: typeof CustoRoute
  DashboardRoute: typeof DashboardRoute
  DerouleRoute: typeof DerouleRoute
  LumieresRoute: typeof LumieresRoute
  MonitoringRoute: typeof MonitoringRoute
  ProgressionRoute: typeof ProgressionRoute
  ReseauRoute: typeof ReseauRoute
  ResolutionsRoute: typeof ResolutionsRoute
  ScoreboardRoute: typeof ScoreboardRoute
  ScoringRoute: typeof ScoringRoute
  SonRoute: typeof SonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/son': {
      id: '/son'
      path: '/son'
      fullPath: '/son'
      preLoaderRoute: typeof SonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoring': {
      id: '/scoring'
      path: '/scoring'
      fullPath: '/scoring'
      preLoaderRoute: typeof ScoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoreboard': {
      id: '/scoreboard'
      path: '/scoreboard'
      fullPath: '/scoreboard'
      preLoaderRoute: typeof ScoreboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resolutions': {
      id: '/resolutions'
      path: '/resolutions'
      fullPath: '/resolutions'
      preLoaderRoute: typeof ResolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reseau': {
      id: '/reseau'
      path: '/reseau'
      fullPath: '/reseau'
      preLoaderRoute: typeof ReseauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progression': {
      id: '/progression'
      path: '/progression'
      fullPath: '/progression'
      preLoaderRoute: typeof ProgressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lumieres': {
      id: '/lumieres'
      path: '/lumieres'
      fullPath: '/lumieres'
      preLoaderRoute: typeof LumieresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deroule': {
      id: '/deroule'
      path: '/deroule'
      fullPath: '/deroule'
      preLoaderRoute: typeof DerouleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custo': {
      id: '/custo'
      path: '/custo'
      fullPath: '/custo'
      preLoaderRoute: typeof CustoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chrono': {
      id: '/chrono'
      path: '/chrono'
      fullPath: '/chrono'
      preLoaderRoute: typeof ChronoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cameras': {
      id: '/cameras'
      path: '/cameras'
      fullPath: '/cameras'
      preLoaderRoute: typeof CamerasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accueil': {
      id: '/accueil'
      path: '/accueil'
      fullPath: '/accueil'
      preLoaderRoute: typeof AccueilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acces': {
      id: '/acces'
      path: '/acces'
      fullPath: '/acces'
      preLoaderRoute: typeof AccesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccesRoute: AccesRoute,
  AccueilRoute: AccueilRoute,
  CamerasRoute: CamerasRoute,
  ChallengesRoute: ChallengesRoute,
  ChronoRoute: ChronoRoute,
  CustoRoute: CustoRoute,
  DashboardRoute: DashboardRoute,
  DerouleRoute: DerouleRoute,
  LumieresRoute: LumieresRoute,
  MonitoringRoute: MonitoringRoute,
  ProgressionRoute: ProgressionRoute,
  ReseauRoute: ReseauRoute,
  ResolutionsRoute: ResolutionsRoute,
  ScoreboardRoute: ScoreboardRoute,
  ScoringRoute: ScoringRoute,
  SonRoute: SonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
